### PR TITLE
Finalize

### PR DESCRIPTION
**Pull request by LinguList**
@arubehn, please consider this PR, which makes this a single-file package. Experimenting with it, I found that it is much easier to make only one file, clts2vec.py, and install this as one package, with zero dependencies, which is quite important to keep it also flexible for reuse in the future.

### CODE REVIEW

**Comment by LinguList** [comment]
In the tests, I added a fake CLTS class, which mimicks the CLTS behaviour, and this allows us to handle tests now even in the cases where we want to check for `sound.name`.

**Comment by LinguList** [comment]
I also added a guideline for RELEASING (taken from guidelines Robert used in his projects).

**Comment by LinguList** [comment]
If we agree on a final version by the end of the week, we can submit this to pypi. This means, installing is just typing `pip install clts2vec`, and since it is such a small package and so clear in usage, even without CLTS, it has many merits.

Thanks for the tests, by the way, they made my life easy this time :-)

**Comment by arubehn** [comment]
I just checked out your branch - what happened to the `features.py` file? It looks like it was deleted from VC - did you maybe forget to commit it?

**Comment by arubehn** [comment]
Nevermind, I just saw that you merged that in the latest commit :)

**Comment by LinguList** [comment]
I suggest I merge now, so we can look into the tutorial and some other points for now, and plan on submitting the package to pypi on Friday (or earlier even, if we feel like it).

**Pull request merged**
